server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: log/promtail-positions.yml

clients:
  - url: ${LOKI_URL}

scrape_configs:
  - job_name: miniwow-file-logs
    static_configs:
      - targets: [localhost]
        labels:
          app: miniwow
          __path__: log/autodungeon_*.log
    pipeline_stages:
      - regex:
          expression: '^\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}\.\d{3}\s+\w+\s+(?P<config>\S+)\s+(?P<emulator>\S+)'
      - labels:
          config:
          emulator:
      - regex:
          source: filename
          expression: '.*/autodungeon_(?P<emulator_underscore>[^.]+)\.log$'
      - template:
          source: emulator_underscore
          template: '{{ Replace .Value "_" ":" -1 }}'
          target: emulator
      - labels:
          emulator:
