server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: log/promtail-positions.yml

clients:
  - url: ${LOKI_URL}

scrape_configs:
  - job_name: miniwow-file-logs
    static_configs:
      - targets: [localhost]
        labels:
          app: miniwow
          __path__: log/[0-9]*.log
      - targets: [localhost]
        labels:
          app: miniwow
          __path__: log/unknown.log
    pipeline_stages:
      - regex:
          expression: '^[0-9]{4}-[0-9]{2}-[0-9]{2}[^ ]*\s+\w+\s+(?P<config>\S+)\s+(?P<emulator>\S+)'
      - labels:
          config:
          emulator:
  - job_name: miniwow-shell-logs
    static_configs:
      - targets: [localhost]
        labels:
          app: miniwow
          origin: shell
          __path__: log/shell_*.log
    pipeline_stages:
      - regex:
          source: filename
          expression: '.*/shell_(?P<session>[^.]+)\.log$'
      - labels:
          origin:
          session:
